import type { AppEdge, AppNode, CableData } from '../types/electrical';

export interface SchematicPreset {
  id: string;
  name: string;
  description: string;
  category: 'lighting' | 'switched' | 'protection' | 'power';
  nodes: AppNode[];
  edges: AppEdge[];
}

export const PRESET_CIRCUITS: Record<string, SchematicPreset> = {
  simple_light: {
    id: 'simple_light',
    name: 'Alumbrado Simple',
    description: 'Circuito básico: Fuente 230V, magnetotérmico 10A, interruptor unipolar y lámpara.',
    category: 'lighting',
    nodes: [
      {
        id: 'node-source-1',
        type: 'sourceNode',
        position: { x: 50, y: 180 },
        data: {
          id: 'node-source-1',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-breaker-1',
        type: 'breakerNode',
        position: { x: 300, y: 170 },
        data: {
          id: 'node-breaker-1',
          name: 'PIA 10A Alumbrado',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-switch-1',
        type: 'switchNode',
        position: { x: 550, y: 130 },
        data: {
          id: 'node-switch-1',
          name: 'Interruptor S1',
          type: 'switch',
          switchType: 'single_pole',
          position: 'closed',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Retorno', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
          ],
        },
      },
      {
        id: 'node-lamp-1',
        type: 'loadNode',
        position: { x: 800, y: 180 },
        data: {
          id: 'node-lamp-1',
          name: 'Lámpara LED 15W',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 15,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.07,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l',
        source: 'node-source-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n',
        source: 'node-source-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw',
        source: 'node-breaker-1',
        target: 'node-switch-1',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-lamp',
        source: 'node-switch-1',
        target: 'node-lamp-1',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n',
        source: 'node-lamp-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  two_way_switch: {
    id: 'two_way_switch',
    name: 'Conmutada 2 Puntos',
    description: 'Circuito conmutado típico de pasillo/dormitorio con 2 conmutadores que controlan la misma lámpara.',
    category: 'switched',
    nodes: [
      {
        id: 'node-src-tw',
        type: 'sourceNode',
        position: { x: 40, y: 220 },
        data: {
          id: 'node-src-tw',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-tw',
        type: 'breakerNode',
        position: { x: 260, y: 210 },
        data: {
          id: 'node-brk-tw',
          name: 'PIA 10A Iluminación',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-tw',
        type: 'switchNode',
        position: { x: 490, y: 160 },
        data: {
          id: 'node-sw1-tw',
          name: 'Conmutador Q1',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-tw',
        type: 'switchNode',
        position: { x: 740, y: 160 },
        data: {
          id: 'node-sw2-tw',
          name: 'Conmutador Q2',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-tw',
        type: 'loadNode',
        position: { x: 990, y: 220 },
        data: {
          id: 'node-lamp-tw',
          name: 'Punto de Luz Central',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 40,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.17,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-tw',
        source: 'node-src-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-tw',
        source: 'node-src-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw1-tw',
        source: 'node-brk-tw',
        target: 'node-sw1-tw',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-sw2-l1',
        source: 'node-sw1-tw',
        target: 'node-sw2-tw',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-sw2-l2',
        source: 'node-sw1-tw',
        target: 'node-sw2-tw',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-tw',
        source: 'node-sw2-tw',
        target: 'node-lamp-tw',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n-tw',
        source: 'node-lamp-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  intermediate_switch: {
    id: 'intermediate_switch',
    name: 'Conmutada de Cruce (3 Puntos)',
    description: 'Control de luz desde 3 puntos: 2 conmutadores de extremo y 1 llave de cruce intermedia.',
    category: 'switched',
    nodes: [
      {
        id: 'node-src-cr',
        type: 'sourceNode',
        position: { x: 30, y: 220 },
        data: {
          id: 'node-src-cr',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-cr',
        type: 'breakerNode',
        position: { x: 230, y: 210 },
        data: {
          id: 'node-brk-cr',
          name: 'PIA 10A Iluminación',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-cr',
        type: 'switchNode',
        position: { x: 440, y: 160 },
        data: {
          id: 'node-sw1-cr',
          name: 'Conmutador Q1',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-cross-1',
        type: 'switchNode',
        position: { x: 670, y: 160 },
        data: {
          id: 'node-cross-1',
          name: 'Cruzamiento QX',
          type: 'switch',
          switchType: 'intermediate',
          position: 'straight',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-cr-in1', name: 'Entrada 1', role: 'in', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-in2', name: 'Entrada 2', role: 'in', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
            { id: 'term-cr-out1', name: 'Salida 1', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-out2', name: 'Salida 2', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-cr',
        type: 'switchNode',
        position: { x: 910, y: 160 },
        data: {
          id: 'node-sw2-cr',
          name: 'Conmutador Q2',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-cr',
        type: 'loadNode',
        position: { x: 1140, y: 220 },
        data: {
          id: 'node-lamp-cr',
          name: 'Lámpara Techo',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 60,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.26,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-cr',
        source: 'node-src-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-cr',
        source: 'node-src-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw1-cr',
        source: 'node-brk-cr',
        target: 'node-sw1-cr',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr-l1',
        source: 'node-sw1-cr',
        target: 'node-cross-1',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-cr-in1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr-l2',
        source: 'node-sw1-cr',
        target: 'node-cross-1',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-cr-in2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-cr-sw2-l1',
        source: 'node-cross-1',
        target: 'node-sw2-cr',
        sourceHandle: 'term-cr-out1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-cr-sw2-l2',
        source: 'node-cross-1',
        target: 'node-sw2-cr',
        sourceHandle: 'term-cr-out2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-cr',
        source: 'node-sw2-cr',
        target: 'node-lamp-cr',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n-cr',
        source: 'node-lamp-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  short_circuit_demo: {
    id: 'short_circuit_demo',
    name: 'Demo Cortocircuito y Sección',
    description: 'Demostración de disparo de disyuntor por cortocircuito directo y advertencia por cable de 1.5 mm² en magneto de 25A.',
    category: 'protection',
    nodes: [
      {
        id: 'node-src-short',
        type: 'sourceNode',
        position: { x: 50, y: 180 },
        data: {
          id: 'node-src-short',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-short',
        type: 'breakerNode',
        position: { x: 300, y: 170 },
        data: {
          id: 'node-brk-short',
          name: 'PIA 25A (Sobredimensionado)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 25,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-switch-short',
        type: 'switchNode',
        position: { x: 560, y: 170 },
        data: {
          id: 'node-switch-short',
          name: 'Interruptor de Prueba',
          type: 'switch',
          switchType: 'single_pole',
          position: 'open',
          isPressed: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Salida', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-sc',
        source: 'node-src-short',
        target: 'node-brk-short',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-sc',
        source: 'node-src-short',
        target: 'node-brk-short',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw-sc',
        source: 'node-brk-short',
        target: 'node-switch-short',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-short-direct',
        source: 'node-switch-short',
        target: 'node-brk-short',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
    ],
  },
};
