import type { AppEdge, AppNode, CableData } from '../types/electrical';

export interface SchematicPreset {
  id: string;
  name: string;
  description: string;
  category: 'lighting' | 'switched' | 'protection' | 'power';
  nodes: AppNode[];
  edges: AppEdge[];
}

export const PRESET_CIRCUITS: Record<string, SchematicPreset> = {
  full_house_rebt: {
    id: 'full_house_rebt',
    name: 'Vivienda Completa REBT (5 Circuitos)',
    description: 'Instalación completa reglamentaria (ITC-BT-25): IGA 40A, PCS Sobretensiones, Diferencial 40A/30mA y 5 circuitos (C1 Alumbrado con 2 cruzamientos, C2 Tomas generales, C3 Cocina/Horno, C4 Lavadora/Termo, C5 Baño/Cocina).',
    category: 'power',
    nodes: [
      {
        id: 'node-src-fh',
        type: 'sourceNode',
        position: { x: 80, y: 700},
        data: {
          id: 'node-src-fh',
          name: 'Alimentación Red 230V',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-iga-fh',
        type: 'breakerNode',
        position: { x: 480, y: 700},
        data: {
          id: 'node-iga-fh',
          name: 'IGA 40A General',
          type: 'breaker',
          breakerType: 'iga',
          ratedCurrent: 40,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-pcs-fh',
        type: 'breakerNode',
        position: { x: 880, y: 700},
        data: {
          id: 'node-pcs-fh',
          name: 'PCS Sobretensiones',
          type: 'breaker',
          breakerType: 'pcs',
          ratedCurrent: 40,
          curve: 'C',
          breakingCapacityKa: 10,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-rcd-fh',
        type: 'breakerNode',
        position: { x: 1280, y: 700},
        data: {
          id: 'node-rcd-fh',
          name: 'Diferencial ID 40A 30mA',
          type: 'breaker',
          breakerType: 'rcd',
          ratedCurrent: 40,
          rcdSensitivityMa: 30,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-c1',
        type: 'breakerNode',
        position: { x: 1750, y: 180},
        data: {
          id: 'node-brk-c1',
          name: 'PIA C1 10A (Alumbrado)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-c2',
        type: 'breakerNode',
        position: { x: 1750, y: 700},
        data: {
          id: 'node-brk-c2',
          name: 'PIA C2 16A (Tomas Uso Gral)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 16,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-c3',
        type: 'breakerNode',
        position: { x: 1750, y: 1050},
        data: {
          id: 'node-brk-c3',
          name: 'PIA C3 25A (Cocina/Horno)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 25,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-c4',
        type: 'breakerNode',
        position: { x: 1750, y: 1350},
        data: {
          id: 'node-brk-c4',
          name: 'PIA C4 20A (Lavadora/Termo)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 20,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-c5',
        type: 'breakerNode',
        position: { x: 1750, y: 1650},
        data: {
          id: 'node-brk-c5',
          name: 'PIA C5 16A (Baño y Cocina Aux)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 16,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw-bath',
        type: 'switchNode',
        position: { x: 2250, y: -40},
        data: {
          id: 'node-sw-bath',
          name: 'Interruptor Baño',
          type: 'switch',
          switchType: 'single_pole',
          position: 'closed',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Retorno', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
          ],
        },
      },
      {
        id: 'node-lamp-bath',
        type: 'loadNode',
        position: { x: 2750, y: -40},
        data: {
          id: 'node-lamp-bath',
          name: 'Lámpara LED Baño 15W',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 15,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.07,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-q1',
        type: 'switchNode',
        position: { x: 2250, y: 140},
        data: {
          id: 'node-sw1-q1',
          name: 'Conmutador Q1 Puerta',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-cr-q1',
        type: 'switchNode',
        position: { x: 2750, y: 140},
        data: {
          id: 'node-cr-q1',
          name: 'Cruzamiento Q1 Cabecero',
          type: 'switch',
          switchType: 'intermediate',
          position: 'straight',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-cr-in1', name: 'Entrada 1', role: 'in', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-in2', name: 'Entrada 2', role: 'in', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
            { id: 'term-cr-out1', name: 'Salida 1', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-out2', name: 'Salida 2', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-q1',
        type: 'switchNode',
        position: { x: 3250, y: 140},
        data: {
          id: 'node-sw2-q1',
          name: 'Conmutador Q1 Mesita',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-q1',
        type: 'loadNode',
        position: { x: 3750, y: 140},
        data: {
          id: 'node-lamp-q1',
          name: 'Lámpara Cuarto 1 (40W)',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 40,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.17,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-q2',
        type: 'switchNode',
        position: { x: 2250, y: 320},
        data: {
          id: 'node-sw1-q2',
          name: 'Conmutador Q2 Puerta',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-cr-q2',
        type: 'switchNode',
        position: { x: 2750, y: 320},
        data: {
          id: 'node-cr-q2',
          name: 'Cruzamiento Q2 Intermedio',
          type: 'switch',
          switchType: 'intermediate',
          position: 'straight',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-cr-in1', name: 'Entrada 1', role: 'in', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-in2', name: 'Entrada 2', role: 'in', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
            { id: 'term-cr-out1', name: 'Salida 1', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-out2', name: 'Salida 2', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-q2',
        type: 'switchNode',
        position: { x: 3250, y: 320},
        data: {
          id: 'node-sw2-q2',
          name: 'Conmutador Q2 Cama',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-q2',
        type: 'loadNode',
        position: { x: 3750, y: 320},
        data: {
          id: 'node-lamp-q2',
          name: 'Lámpara Cuarto 2 (40W)',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 40,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.17,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw-living',
        type: 'switchNode',
        position: { x: 2250, y: 500},
        data: {
          id: 'node-sw-living',
          name: 'Interruptor Salón',
          type: 'switch',
          switchType: 'single_pole',
          position: 'closed',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Retorno', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
          ],
        },
      },
      {
        id: 'node-lamp-living',
        type: 'loadNode',
        position: { x: 2750, y: 500},
        data: {
          id: 'node-lamp-living',
          name: 'Lámpara LED Salón (60W)',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 60,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.26,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw-kitchen',
        type: 'switchNode',
        position: { x: 3250, y: 500},
        data: {
          id: 'node-sw-kitchen',
          name: 'Interruptor Cocina',
          type: 'switch',
          switchType: 'single_pole',
          position: 'closed',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Retorno', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
          ],
        },
      },
      {
        id: 'node-lamp-kitchen',
        type: 'loadNode',
        position: { x: 3750, y: 500},
        data: {
          id: 'node-lamp-kitchen',
          name: 'Lámpara LED Cocina (30W)',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 30,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.13,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-living',
        type: 'loadNode',
        position: { x: 2250, y: 700},
        data: {
          id: 'node-sock-living',
          name: 'Toma Salón TV (300W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 300,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 1.30,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-q1',
        type: 'loadNode',
        position: { x: 2750, y: 700},
        data: {
          id: 'node-sock-q1',
          name: 'Toma Mesita Cuarto 1 (150W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 150,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.65,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-q2',
        type: 'loadNode',
        position: { x: 3250, y: 700},
        data: {
          id: 'node-sock-q2',
          name: 'Toma Escritorio Cuarto 2 (150W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 150,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.65,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-c3',
        type: 'loadNode',
        position: { x: 2250, y: 1050},
        data: {
          id: 'node-sock-c3',
          name: 'Toma Horno / Placa (3000W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 3000,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 13.04,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-c4',
        type: 'loadNode',
        position: { x: 2250, y: 1350},
        data: {
          id: 'node-sock-c4',
          name: 'Toma Lavadora / Termo (2000W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 2000,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 8.70,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-bath',
        type: 'loadNode',
        position: { x: 2250, y: 1650},
        data: {
          id: 'node-sock-bath',
          name: 'Toma Baño Lavabo (1200W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 1200,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 5.22,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sock-kitchen-aux',
        type: 'loadNode',
        position: { x: 2750, y: 1650},
        data: {
          id: 'node-sock-kitchen-aux',
          name: 'Toma Encimera Cocina (800W)',
          type: 'load',
          loadType: 'socket',
          ratedPowerWatts: 800,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 3.48,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-iga-l',
        source: 'node-src-fh',
        target: 'node-iga-fh',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-iga-n',
        source: 'node-src-fh',
        target: 'node-iga-fh',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-iga-pcs-l',
        source: 'node-iga-fh',
        target: 'node-pcs-fh',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-iga-pcs-n',
        source: 'node-iga-fh',
        target: 'node-pcs-fh',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-pcs-rcd-l',
        source: 'node-pcs-fh',
        target: 'node-rcd-fh',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-pcs-rcd-n',
        source: 'node-pcs-fh',
        target: 'node-rcd-fh',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c1-l',
        source: 'node-rcd-fh',
        target: 'node-brk-c1',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c1-n',
        source: 'node-rcd-fh',
        target: 'node-brk-c1',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c2-l',
        source: 'node-rcd-fh',
        target: 'node-brk-c2',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c2-n',
        source: 'node-rcd-fh',
        target: 'node-brk-c2',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c3-l',
        source: 'node-rcd-fh',
        target: 'node-brk-c3',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c3-n',
        source: 'node-rcd-fh',
        target: 'node-brk-c3',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c4-l',
        source: 'node-rcd-fh',
        target: 'node-brk-c4',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c4-n',
        source: 'node-rcd-fh',
        target: 'node-brk-c4',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c5-l',
        source: 'node-rcd-fh',
        target: 'node-brk-c5',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-rcd-c5-n',
        source: 'node-rcd-fh',
        target: 'node-brk-c5',
        sourceHandle: 'term-n-out',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 10.0, maxAllowedCurrentAmps: 50, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c1-bath-l',
        source: 'node-brk-c1',
        target: 'node-sw-bath',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-bath-lamp',
        source: 'node-sw-bath',
        target: 'node-lamp-bath',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-bath-n',
        source: 'node-lamp-bath',
        target: 'node-brk-c1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c1-q1-l',
        source: 'node-brk-c1',
        target: 'node-sw1-q1',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr1-1',
        source: 'node-sw1-q1',
        target: 'node-cr-q1',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-cr-in1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr1-2',
        source: 'node-sw1-q1',
        target: 'node-cr-q1',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-cr-in2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-cr1-sw2-1',
        source: 'node-cr-q1',
        target: 'node-sw2-q1',
        sourceHandle: 'term-cr-out1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-cr1-sw2-2',
        source: 'node-cr-q1',
        target: 'node-sw2-q1',
        sourceHandle: 'term-cr-out2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-q1',
        source: 'node-sw2-q1',
        target: 'node-lamp-q1',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-q1-n',
        source: 'node-lamp-q1',
        target: 'node-brk-c1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c1-q2-l',
        source: 'node-brk-c1',
        target: 'node-sw1-q2',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr2-1',
        source: 'node-sw1-q2',
        target: 'node-cr-q2',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-cr-in1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr2-2',
        source: 'node-sw1-q2',
        target: 'node-cr-q2',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-cr-in2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-cr2-sw2-1',
        source: 'node-cr-q2',
        target: 'node-sw2-q2',
        sourceHandle: 'term-cr-out1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-cr2-sw2-2',
        source: 'node-cr-q2',
        target: 'node-sw2-q2',
        sourceHandle: 'term-cr-out2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-q2',
        source: 'node-sw2-q2',
        target: 'node-lamp-q2',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-q2-n',
        source: 'node-lamp-q2',
        target: 'node-brk-c1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c1-living-l',
        source: 'node-brk-c1',
        target: 'node-sw-living',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-living-lamp',
        source: 'node-sw-living',
        target: 'node-lamp-living',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-living-n',
        source: 'node-lamp-living',
        target: 'node-brk-c1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c1-kitchen-l',
        source: 'node-brk-c1',
        target: 'node-sw-kitchen',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-kitchen-lamp',
        source: 'node-sw-kitchen',
        target: 'node-lamp-kitchen',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-kitchen-n',
        source: 'node-lamp-kitchen',
        target: 'node-brk-c1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-living-l',
        source: 'node-brk-c2',
        target: 'node-sock-living',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-living-n',
        source: 'node-sock-living',
        target: 'node-brk-c2',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-q1-l',
        source: 'node-brk-c2',
        target: 'node-sock-q1',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-q1-n',
        source: 'node-sock-q1',
        target: 'node-brk-c2',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-q2-l',
        source: 'node-brk-c2',
        target: 'node-sock-q2',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c2-sock-q2-n',
        source: 'node-sock-q2',
        target: 'node-brk-c2',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c3-sock-l',
        source: 'node-brk-c3',
        target: 'node-sock-c3',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 6.0, maxAllowedCurrentAmps: 32, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c3-sock-n',
        source: 'node-sock-c3',
        target: 'node-brk-c3',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 6.0, maxAllowedCurrentAmps: 32, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c4-sock-l',
        source: 'node-brk-c4',
        target: 'node-sock-c4',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 4.0, maxAllowedCurrentAmps: 25, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c4-sock-n',
        source: 'node-sock-c4',
        target: 'node-brk-c4',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 4.0, maxAllowedCurrentAmps: 25, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c5-sock-bath-l',
        source: 'node-brk-c5',
        target: 'node-sock-bath',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c5-sock-bath-n',
        source: 'node-sock-bath',
        target: 'node-brk-c5',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-c5-sock-kit-l',
        source: 'node-brk-c5',
        target: 'node-sock-kitchen-aux',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-c5-sock-kit-n',
        source: 'node-sock-kitchen-aux',
        target: 'node-brk-c5',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 2.5, maxAllowedCurrentAmps: 20, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },
  simple_light: {
    id: 'simple_light',
    name: 'Alumbrado Simple',
    description: 'Circuito básico: Fuente 230V, magnetotérmico 10A, interruptor unipolar y lámpara.',
    category: 'lighting',
    nodes: [
      {
        id: 'node-source-1',
        type: 'sourceNode',
        position: { x: 100, y: 240},
        data: {
          id: 'node-source-1',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-breaker-1',
        type: 'breakerNode',
        position: { x: 500, y: 240},
        data: {
          id: 'node-breaker-1',
          name: 'PIA 10A Alumbrado',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-switch-1',
        type: 'switchNode',
        position: { x: 960, y: 240},
        data: {
          id: 'node-switch-1',
          name: 'Interruptor S1',
          type: 'switch',
          switchType: 'single_pole',
          position: 'closed',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Retorno', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
          ],
        },
      },
      {
        id: 'node-lamp-1',
        type: 'loadNode',
        position: { x: 1440, y: 240},
        data: {
          id: 'node-lamp-1',
          name: 'Lámpara LED 15W',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 15,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.07,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l',
        source: 'node-source-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n',
        source: 'node-source-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw',
        source: 'node-breaker-1',
        target: 'node-switch-1',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-lamp',
        source: 'node-switch-1',
        target: 'node-lamp-1',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n',
        source: 'node-lamp-1',
        target: 'node-breaker-1',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  two_way_switch: {
    id: 'two_way_switch',
    name: 'Conmutada 2 Puntos',
    description: 'Circuito conmutado típico de pasillo/dormitorio con 2 conmutadores que controlan la misma lámpara.',
    category: 'switched',
    nodes: [
      {
        id: 'node-src-tw',
        type: 'sourceNode',
        position: { x: 100, y: 240},
        data: {
          id: 'node-src-tw',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-tw',
        type: 'breakerNode',
        position: { x: 500, y: 240},
        data: {
          id: 'node-brk-tw',
          name: 'PIA 10A Iluminación',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-tw',
        type: 'switchNode',
        position: { x: 960, y: 240},
        data: {
          id: 'node-sw1-tw',
          name: 'Conmutador Q1',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-tw',
        type: 'switchNode',
        position: { x: 1480, y: 240},
        data: {
          id: 'node-sw2-tw',
          name: 'Conmutador Q2',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-tw',
        type: 'loadNode',
        position: { x: 2000, y: 240},
        data: {
          id: 'node-lamp-tw',
          name: 'Punto de Luz Central',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 40,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.17,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-tw',
        source: 'node-src-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-tw',
        source: 'node-src-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw1-tw',
        source: 'node-brk-tw',
        target: 'node-sw1-tw',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-sw2-l1',
        source: 'node-sw1-tw',
        target: 'node-sw2-tw',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-sw2-l2',
        source: 'node-sw1-tw',
        target: 'node-sw2-tw',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-tw',
        source: 'node-sw2-tw',
        target: 'node-lamp-tw',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n-tw',
        source: 'node-lamp-tw',
        target: 'node-brk-tw',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  intermediate_switch: {
    id: 'intermediate_switch',
    name: 'Conmutada de Cruce (3 Puntos)',
    description: 'Control de luz desde 3 puntos: 2 conmutadores de extremo y 1 llave de cruce intermedia.',
    category: 'switched',
    nodes: [
      {
        id: 'node-src-cr',
        type: 'sourceNode',
        position: { x: 100, y: 240},
        data: {
          id: 'node-src-cr',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-cr',
        type: 'breakerNode',
        position: { x: 500, y: 240},
        data: {
          id: 'node-brk-cr',
          name: 'PIA 10A Iluminación',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 10,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw1-cr',
        type: 'switchNode',
        position: { x: 960, y: 240},
        data: {
          id: 'node-sw1-cr',
          name: 'Conmutador Q1',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-cross-1',
        type: 'switchNode',
        position: { x: 1480, y: 240},
        data: {
          id: 'node-cross-1',
          name: 'Cruzamiento QX',
          type: 'switch',
          switchType: 'intermediate',
          position: 'straight',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-cr-in1', name: 'Entrada 1', role: 'in', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-in2', name: 'Entrada 2', role: 'in', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
            { id: 'term-cr-out1', name: 'Salida 1', role: 'out', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-cr-out2', name: 'Salida 2', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-sw2-cr',
        type: 'switchNode',
        position: { x: 2000, y: 240},
        data: {
          id: 'node-sw2-cr',
          name: 'Conmutador Q2',
          type: 'switch',
          switchType: 'two_way',
          position: 'pos_1',
          isPressed: false,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-sw-com', name: 'Común', role: 'common', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-l1', name: 'Viajero 1', role: 'traveler_1', polarity: 'VARIABLE', isEnergized: true, potential: 230 },
            { id: 'term-sw-l2', name: 'Viajero 2', role: 'traveler_2', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-lamp-cr',
        type: 'loadNode',
        position: { x: 2520, y: 240},
        data: {
          id: 'node-lamp-cr',
          name: 'Lámpara Techo',
          type: 'load',
          loadType: 'lamp',
          ratedPowerWatts: 60,
          nominalVoltage: 230,
          isOn: true,
          currentDrawAmps: 0.26,
          isEnergized: true,
          status: 'active',
          terminals: [
            { id: 'term-load-l', name: 'Fase (L)', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-load-n', name: 'Neutro (N)', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-cr',
        source: 'node-src-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-cr',
        source: 'node-src-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw1-cr',
        source: 'node-brk-cr',
        target: 'node-sw1-cr',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-com',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr-l1',
        source: 'node-sw1-cr',
        target: 'node-cross-1',
        sourceHandle: 'term-sw-l1',
        targetHandle: 'term-cr-in1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw1-cr-l2',
        source: 'node-sw1-cr',
        target: 'node-cross-1',
        sourceHandle: 'term-sw-l2',
        targetHandle: 'term-cr-in2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-cr-sw2-l1',
        source: 'node-cross-1',
        target: 'node-sw2-cr',
        sourceHandle: 'term-cr-out1',
        targetHandle: 'term-sw-l1',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-cr-sw2-l2',
        source: 'node-cross-1',
        target: 'node-sw2-cr',
        sourceHandle: 'term-cr-out2',
        targetHandle: 'term-sw-l2',
        type: 'electricalEdge',
        data: { wireType: 'traveler', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-sw2-lamp-cr',
        source: 'node-sw2-cr',
        target: 'node-lamp-cr',
        sourceHandle: 'term-sw-com',
        targetHandle: 'term-load-l',
        type: 'electricalEdge',
        data: { wireType: 'switched_phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-lamp-brk-n-cr',
        source: 'node-lamp-cr',
        target: 'node-brk-cr',
        sourceHandle: 'term-load-n',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: true, isEnergized: false, isShortCircuited: false },
      },
    ],
  },

  short_circuit_demo: {
    id: 'short_circuit_demo',
    name: 'Demo Cortocircuito y Sección',
    description: 'Demostración de disparo de disyuntor por cortocircuito directo y advertencia por cable de 1.5 mm² en magneto de 25A.',
    category: 'protection',
    nodes: [
      {
        id: 'node-src-short',
        type: 'sourceNode',
        position: { x: 120, y: 240},
        data: {
          id: 'node-src-short',
          name: 'Alimentación Red',
          type: 'source',
          voltage: 230,
          frequency: 50,
          isAc: true,
          isPowered: true,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-src-l', name: 'L (Fase)', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-src-n', name: 'N (Neutro)', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-src-pe', name: 'PE (Tierra)', role: 'ground', polarity: 'PE', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-brk-short',
        type: 'breakerNode',
        position: { x: 560, y: 240},
        data: {
          id: 'node-brk-short',
          name: 'PIA 25A (Sobredimensionado)',
          type: 'breaker',
          breakerType: 'circuit_breaker',
          ratedCurrent: 25,
          curve: 'C',
          breakingCapacityKa: 6,
          isClosed: true,
          isTripped: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-l-in', name: 'L Entrada', role: 'phase_in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-l-out', name: 'L Salida', role: 'phase_out', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-n-in', name: 'N Entrada', role: 'neutral_in', polarity: 'N', isEnergized: false, potential: 0 },
            { id: 'term-n-out', name: 'N Salida', role: 'neutral_out', polarity: 'N', isEnergized: false, potential: 0 },
          ],
        },
      },
      {
        id: 'node-switch-short',
        type: 'switchNode',
        position: { x: 1060, y: 240},
        data: {
          id: 'node-switch-short',
          name: 'Interruptor de Prueba',
          type: 'switch',
          switchType: 'single_pole',
          position: 'open',
          isPressed: false,
          isEnergized: true,
          status: 'normal',
          terminals: [
            { id: 'term-sw-in', name: 'L Entrada', role: 'in', polarity: 'L', isEnergized: true, potential: 230 },
            { id: 'term-sw-out', name: 'L Salida', role: 'out', polarity: 'VARIABLE', isEnergized: false, potential: 0 },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-src-brk-l-sc',
        source: 'node-src-short',
        target: 'node-brk-short',
        sourceHandle: 'term-src-l',
        targetHandle: 'term-l-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-src-brk-n-sc',
        source: 'node-src-short',
        target: 'node-brk-short',
        sourceHandle: 'term-src-n',
        targetHandle: 'term-n-in',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
      {
        id: 'e-brk-sw-sc',
        source: 'node-brk-short',
        target: 'node-switch-short',
        sourceHandle: 'term-l-out',
        targetHandle: 'term-sw-in',
        type: 'electricalEdge',
        data: { wireType: 'phase', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: true, isShortCircuited: false },
      },
      {
        id: 'e-sw-short-direct',
        source: 'node-switch-short',
        target: 'node-brk-short',
        sourceHandle: 'term-sw-out',
        targetHandle: 'term-n-out',
        type: 'electricalEdge',
        data: { wireType: 'neutral', crossSectionMm2: 1.5, maxAllowedCurrentAmps: 16, hasCurrent: false, isEnergized: false, isShortCircuited: false },
      },
    ],
  },
};
